/*PROCEDIMIENTO ALMACENADO PARA INSERTAR DATOS EN LA TABLA ALQUILER*/

CREATE OR REPLACE PROCEDURE INSERT_ALQUILER (
  p_ALQUILERID IN ALQUILER.ALQUILERID%TYPE,
  p_USUARIO_ID IN ALQUILER.USUARIO_ID%TYPE)
  
IS 
BEGIN
  INSERT INTO ALQUILER (ALQUILERID,USUARIO_ID)
  VALUES (p_ALQUILERID, p_USUARIO_ID);
  
  --COMMINT;
END;  

/*PRUEBA DE INSERT EN TABLA ALQUILER*/
BEGIN
  INSERT_ALQUILER (01,02);
END;

/*PROCEDIMIENTO ALMACENADO PARA INSERTAR DATOS EN LA TABLA BOTEPESCA*/

CREATE OR REPLACE PROCEDURE INSERT_BOTEPESCA (
  p_BOTEID IN BOTEPESCA.BOTEID%TYPE,
  p_DESCRIPCION IN BOTEPESCA.DESCRIPCION%TYPE,
  P_CANTIDADOCUPADAS IN BOTEPESCA.CANTIDADOCUPADAS%TYPE,
  p_PRECIOALQUILER IN BOTEPESCA.PRECIOALQUILER%TYPE,
  p_CAPITAN_ID IN BOTEPESCA.CAPITAN_ID%TYPE,
  p_VEHICULO_ID IN BOTEPESCA.VEHICULO_ID%TYPE)
  
IS 
BEGIN
  INSERT INTO BOTEPESCA (BOTEID,DESCRIPCION,CANTIDADOCUPADAS,PRECIOALQUILER,CAPITAN_ID, VEHICULO_ID )
  VALUES (p_BOTEID,p_DESCRIPCION,p_CANTIDADOCUPADAS,P_PRECIOALQUILER,p_CAPITAN_ID, p_VEHICULO_ID);
  
  --COMMINT;
END;  

/*PRUEBA DE INSERT EN TABLA BOTEPESCA*/
BEGIN
  INSERT_BOTEPESCA (01,'LANCHA RAPIDA',5,85000,01, 01);
END;

/*PROCEDIMIENTO ALMACENADO PARA INSERTAR DATOS EN LA TABLA CAPITAN*/

CREATE OR REPLACE PROCEDURE INSERT_CAPITAN (
  p_CAPITANID IN CAPITAN.CAPITANID%TYPE,
  p_NUMLICENCIA IN CAPITAN.NUMLICENCIA%TYPE,
  P_FECHACONTRATACION IN CAPITAN.FECHACONTRATACION%TYPE,
  p_USUARIO_ID IN CAPITAN.USUARIO_ID%TYPE)
  
IS 
BEGIN
  INSERT INTO CAPITAN (CAPITANID,NUMLICENCIA,FECHACONTRATACION,USUARIO_ID )
  VALUES (p_CAPITANID,p_NUMLICENCIA,p_FECHACONTRATACION,p_USUARIO_ID );
  
  --COMMINT;
END;  

/*PRUEBA DE INSERT EN TABLA CAPITAN*/
BEGIN
  INSERT_CAPITAN (01,7895415,'04-04-2022',01);
END;

/*PROCEDIMIENTO ALMACENADO PARA INSERTAR DATOS EN LA TABLA DETALLEALQUILER*/

CREATE OR REPLACE PROCEDURE INSERT_DETALLEALQUILER (
  p_DETALLEALQUILERID IN DETALLEALQUILER.DETALLEALQUILERID%TYPE,
  p_FECHAALQUILER IN DETALLEALQUILER.FECHAALQUILER%TYPE,
  P_HORAINICIAALQUI IN DETALLEALQUILER.HORAINICIAALQUI%TYPE,
  p_HORAFINALALQUI IN DETALLEALQUILER.HORAFINALALQUI%TYPE,
  p_ALQUILER_ID IN DETALLEALQUILER.ALQUILER_ID%TYPE,
  p_VEHICULO_ID IN DETALLEALQUILER.VEHICULO_ID%TYPE)
  
IS 
BEGIN
  INSERT INTO DETALLEALQUILER (DETALLEALQUILERID,FECHAALQUILER,HORAINICIAALQUI,HORAFINALALQUI,ALQUILER_ID, VEHICULO_ID )
  VALUES (p_DETALLEALQUILERID,p_FECHAALQUILER,p_HORAINICIAALQUI,p_HORAFINALALQUI,p_ALQUILER_ID, p_VEHICULO_ID);
  
  --COMMINT;
END;  

/*PRUEBA DE INSERT EN TABLA DETALLEALQUILER*/
BEGIN
  INSERT_DETALLEALQUILER (01,'04-04-2022','04-04-2022 9:22:23','06-04-2022 9:22:23',01,01 );
END;

/*PROCEDIMIENTO ALMACENADO PARA INSERTAR DATOS EN LA TABLA DETALLEFACTURA*/

CREATE OR REPLACE PROCEDURE INSERT_DETALLEFACTURA (
  p_DETALLEFACTURAID IN DETALLEFACTURA.DETALLEFACTURAID%TYPE,
  p_LINEA IN DETALLEFACTURA.LINEA%TYPE,
  P_MONTOUNITARIO IN DETALLEFACTURA.MONTOUNITARIO%TYPE,
  p_VEHICULO_ID IN DETALLEFACTURA.VEHICULO_ID%TYPE,
  p_FACTURA_ID IN DETALLEFACTURA.FACTURA_ID%TYPE)
  
IS 
BEGIN
  INSERT INTO DETALLEFACTURA (DETALLEFACTURAID,LINEA,MONTOUNITARIO,VEHICULO_ID,FACTURA_ID )
  VALUES (p_DETALLEFACTURAID,p_LINEA,p_MONTOUNITARIO,p_VEHICULO_ID,p_FACTURA_ID);
  
  --COMMINT;
END;  

/*PRUEBA DE INSERT EN TABLA DETALLEFACTURA*/
BEGIN
  INSERT_DETALLEFACTURA (01,01,01,01,01 );
END;

/*PROCEDIMIENTO ALMACENADO PARA SELECCIONAR DATOS DE LA TABLA ALQUILER*/

CREATE OR REPLACE PROCEDURE SELECT_ALQUILER(BOLSA_ALQUILER OUT SYS_REFCURSOR)
AS
BEGIN
OPEN BOLSA_ALQUILER FOR SELECT * FROM ALQUILER;
END;

/*PRUEBA DE IMPRESIÓN SELECT DE LA TABLA ALQUILER*/
VAR BOLSA_ALQUILER REFCURSOR;
EXECUTE SELECT_ALQUILER (:BOLSA_ALQUILER);
PRINT BOLSA_ALQUILER;

/*PROCEDIMIENTO ALMACENADO PARA SELECCIONAR DATOS DE LA TABLA BOTEPESCA*/

CREATE OR REPLACE PROCEDURE SELECT_BOTEPESCA(BOLSA_BOTEPESCA OUT SYS_REFCURSOR)
AS
BEGIN
OPEN BOLSA_BOTEPESCA FOR SELECT * FROM BOTEPESCA;
END;

/*PRUEBA DE IMPRESIÓN SELECT DE LA TABLA BOTEPESCA*/
VAR BOLSA_BOTEPESCA REFCURSOR;
EXECUTE SELECT_BOTEPESCA (:BOLSA_BOTEPESCA);
PRINT BOLSA_BOTEPESCA;

/*PROCEDIMIENTO ALMACENADO PARA SELECCIONAR DATOS DE LA TABLA CAPITAN*/

CREATE OR REPLACE PROCEDURE SELECT_CAPITAN(BOLSA_CAPITAN OUT SYS_REFCURSOR)
AS
BEGIN
OPEN BOLSA_CAPITAN FOR SELECT * FROM CAPITAN;
END;

/*PRUEBA DE IMPRESIÓN SELECT DE LA TABLA CAPITAN*/
VAR BOLSA_CAPITAN REFCURSOR;
EXECUTE SELECT_CAPITAN (:BOLSA_CAPITAN);
PRINT BOLSA_CAPITAN;

/*PROCEDIMIENTO ALMACENADO PARA SELECCIONAR DATOS DE LA TABLA DETALLEALQUILER*/

CREATE OR REPLACE PROCEDURE SELECT_DETALLEALQUILER(BOLSA_DETALLEALQUILER OUT SYS_REFCURSOR)
AS
BEGIN
OPEN BOLSA_DETALLEALQUILER FOR SELECT * FROM DETALLEALQUILER;
END;

/*PRUEBA DE IMPRESIÓN SELECT DE LA TABLA DETALLEALQUILER*/
VAR BOLSA_DETALLEALQUILER REFCURSOR;
EXECUTE SELECT_DETALLEALQUILER (:BOLSA_DETALLEALQUILER);
PRINT BOLSA_DETALLEALQUILER;

/*PROCEDIMIENTO ALMACENADO PARA SELECCIONAR DATOS DE LA TABLA DETALLEFACTURA*/

CREATE OR REPLACE PROCEDURE SELECT_DETALLEFACTURA (BOLSA_DETALLEFACTURA OUT SYS_REFCURSOR)
AS
BEGIN
OPEN BOLSA_DETALLEFACTURA FOR SELECT * FROM DETALLEFACTURA;
END;

/*PRUEBA DE IMPRESIÓN SELECT DE LA TABLA DETALLEFACTURA*/
VAR BOLSA_DETALLEFACTURA REFCURSOR;
EXECUTE SELECT_DETALLEFACTURA (:BOLSA_DETALLEFACTURA);
PRINT BOLSA_DETALLEFACTURA;
