CREATE OR REPLACE PROCEDURE INSERT_USUARIO (
  p_ID IN usuario.usuarioid%TYPE,
  p_PRIMERNOMBRE IN usuario.primernombre%TYPE,
   p_SEGUNDONOMBRE IN usuario.segundonombre%TYPE,
    p_PRIMERAPELLIDO IN usuario.primerapellido%TYPE,
     P_SEGUNDOAPELLIDO IN usuario.segundoapellido%TYPE,
      p_EMAIL IN usuario.email%TYPE,
       p_CONTRASENA IN usuario.contrasena%TYPE,
        p_TELEFONO IN usuario.telefon%TYPE
  )
  
IS 

BEGIN
  INSERT INTO USUARIO 
  VALUES (p_ID, p_PRIMERNOMBRE,p_SEGUNDONOMBRE,p_PRIMERAPELLIDO, 
  P_SEGUNDOAPELLIDO, p_EMAIL, p_CONTRASENA,p_TELEFONO);
  
END;  


BEGIN 
  INSERT_USUARIO(1, 'Juan', 'Carlos','Alvarado','Vasquez', 'jucaralva@gmail.com', '321', '789456');
END; 


--Procedimiento almacenado de vehiculo
CREATE OR REPLACE PROCEDURE INSERT_VEHICULO (
  p_ID IN vehiculo.vehiculoid%TYPE
  )
  
IS 

BEGIN
  INSERT INTO vehiculo 
  VALUES (p_ID);
  
END;  

BEGIN 
 INSERT_VEHICULO(1);
END; 

--Procedimiento almacenado para insertar jetski

CREATE OR REPLACE PROCEDURE INSERT_JETSKI (
  p_ID IN jetski.jetskiid%TYPE,
  p_DESCRIPCION IN jetski.descripcion%TYPE,
   p_CANTIDAD IN jetski.cantidadocupadas%TYPE,
    p_PRECIO IN jetski.precioalquiler%TYPE,
     p_VEHICULO_ID IN jetski.vehiculo_id%TYPE
  )
  
IS 

BEGIN
  INSERT INTO jetski 
  VALUES (p_ID, p_DESCRIPCION,p_CANTIDAD,p_PRECIO, p_VEHICULO_ID);
  
END;  


BEGIN 
  INSERT_JETSKI(1, 'kawassaki 2013',3,20000, 1);
END; 

CREATE OR REPLACE PROCEDURE INSERT_FACTURA (
  p_ID IN factura.facturaid%TYPE,
  p_MONTOTOTAL IN factura.montototal%TYPE,
   p_USUARIOID IN factura.usuario_id%TYPE,
    p_ALQUILERID IN factura.alquiler_id%TYPE
  )
  
IS 

BEGIN
  INSERT INTO factura 
  VALUES (p_ID, p_MONTOTOTAL,p_USUARIOID,p_ALQUILERID);
  
END;  


BEGIN 
  INSERT_FACTURA(1, 50000, 1,2);
END; 

/*PROCEDIMIENTO ALMACENADO PARA SELECCIONAR DATOS DE LA TABLA USUARIO*/

CREATE OR REPLACE PROCEDURE SELECT_USUARIO(BOLSA_USUSARO OUT SYS_REFCURSOR)
AS
BEGIN
OPEN BOLSA_USUSARO FOR SELECT * FROM usuario;
END;

/*PRUEBA DE IMPRESIÓN SELECT DE LA TABLA CAPITAN*/
VAR BOLSA_USUSARO REFCURSOR;
EXECUTE SELECT_USUARIO (:BOLSA_USUSARO);
PRINT BOLSA_USUSARO;


/*PROCEDIMIENTO ALMACENADO PARA SELECCIONAR DATOS DE LA TABLA VEHICULO*/

CREATE OR REPLACE PROCEDURE SELECT_VEHICULO(BOLSA_VEHICULO OUT SYS_REFCURSOR)
AS
BEGIN
OPEN BOLSA_USUSARO FOR SELECT * FROM vehiculo;
END;

/*PRUEBA DE IMPRESIÓN SELECT DE LA TABLA CAPITAN*/
VAR BOLSA_VEHICULO REFCURSOR;
EXECUTE SELECT_VEHICULO (:BOLSA_VEHICULO);
PRINT BOLSA_VEHICULO;


/*PROCEDIMIENTO ALMACENADO PARA SELECCIONAR DATOS DE LA TABLA JETSKI*/

CREATE OR REPLACE PROCEDURE SELECT_JETSKI(BOLSA_JETSKI OUT SYS_REFCURSOR)
AS
BEGIN
OPEN BOLSA_USUSARO FOR SELECT * FROM jetski;
END;

/*PRUEBA DE IMPRESIÓN SELECT DE LA TABLA CAPITAN*/
VAR BOLSA_JETSKI REFCURSOR;
EXECUTE SELECT_JETSKI (:BOLSA_JETSKI);
PRINT BOLSA_JETSKI;


/*PROCEDIMIENTO ALMACENADO PARA SELECCIONAR DATOS DE LA TABLA FACTURA*/

CREATE OR REPLACE PROCEDURE SELECT_FACTURA(BOLSA_FACTURA OUT SYS_REFCURSOR)
AS
BEGIN
OPEN BOLSA_USUSARO FOR SELECT * FROM factura;
END;

/*PRUEBA DE IMPRESIÓN SELECT DE LA TABLA CAPITAN*/
VAR BOLSA_FACTURA REFCURSOR;
EXECUTE SELECT_FACTURA (:BOLSA_FACTURA);
PRINT BOLSA_FACTURA;